In [0]:
pip install faker pandas

Collecting faker
  Downloading faker-40.31.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: pandas in /databricks/python3/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /databricks/python3/lib/python3.12/site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /databricks/python3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /databricks/python3/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /databricks/python3/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /databricks/python3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading faker-40.31.0-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 45.4 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.31.0
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
import random
from faker import Faker
from datetime import datetime, timedelta
import pandas as pd

fake = Faker()

random.seed(42)
Faker.seed(42)

In [0]:
NUM_CUSTOMERS = 500
NUM_PRODUCTS = 500
NUM_ORDERS = 500
NUM_ORDER_ITEMS = 1000

In [0]:
customer_types = ["REGULAR", "PREMIUM", "VIP"]

customers = []

for i in range(1, NUM_CUSTOMERS + 1):

    customers.append({
        "customer_id": i,
        "customer_name": fake.name(),
        "email": fake.email(),
        "registration_date": fake.date_between(
            start_date="-3y",
            end_date="today"
        ),
        "customer_type": random.choice(customer_types)
    })

In [0]:
num_invalid = int(NUM_CUSTOMERS * 0.02)
indices = random.sample(range(NUM_CUSTOMERS), num_invalid)
for i in indices:
    customers[i]["email"] = customers[i]["email"].replace("@", "")

In [0]:
customers_df = pd.DataFrame(customers)
customers_df.head()

   customer_id      customer_name  ... registration_date customer_type
0            1       Allison Hill  ...        2026-03-22       PREMIUM
1            2     Javier Johnson  ...        2024-02-21       REGULAR
2            3  Kimberly Robinson  ...        2024-10-24       REGULAR
3            4   Daniel Gallagher  ...        2025-05-10       PREMIUM
4            5     Monica Herrera  ...        2025-05-26       REGULAR

[5 rows x 5 columns]

In [0]:
categories = {

    "Electronics": [
        "Laptop",
        "Phone",
        "Camera",
        "Headphones",
        "Monitor"
    ],

    "Clothing": [
        "Shirt",
        "Jeans",
        "Jacket",
        "Dress",
        "T-Shirt"
    ],

    "Books": [
        "Novel",
        "Biography",
        "Dictionary",
        "Magazine",
        "Comics"
    ],

    "Home": [
        "Chair",
        "Table",
        "Lamp",
        "Fan",
        "Sofa"
    ]
}

In [0]:
products = []
for i in range(1, NUM_PRODUCTS + 1):
    category = random.choice(list(categories.keys()))
    product = random.choice(categories[category])
    products.append({
        "product_id": i,
        "product_name": product,
        "category": category,
        "subcategory": product,
        "cost_price": round(
            random.uniform(100, 5000), 2
        )
    })

In [0]:
num_dirty = int(NUM_PRODUCTS * 0.03)

indices = random.sample(range(NUM_PRODUCTS), num_dirty)

for i in indices:

    choice = random.randint(1,3)

    if choice == 1:
        products[i]["product_name"] = "  " + products[i]["product_name"] + "  "

    elif choice == 2:
        products[i]["product_name"] = products[i]["product_name"].upper()

    else:
        products[i]["product_name"] = products[i]["product_name"].lower()

In [0]:
products_df = pd.DataFrame(products)

products_df.head()

   product_id product_name     category subcategory  cost_price
0           1        Chair         Home       Chair     3596.37
1           2       Jacket     Clothing      Jacket     1745.65
2           3        Phone  Electronics       Phone      839.07
3           4        Table         Home       Table     3561.45
4           5   Headphones  Electronics  Headphones     2097.24

In [0]:
statuses = [
    "PLACED",
    "SHIPPED",
    "DELIVERED",
    "CANCELLED",
    "RETURNED"
]

regions = [
    "NORTH",
    "SOUTH",
    "EAST",
    "WEST"
]

In [0]:
orders = []

for i in range(1, NUM_ORDERS + 1):

    dt = fake.date_time_between(
        start_date="-2y",
        end_date="now"
    )

    orders.append({

        "order_id": i,

        "customer_id": random.randint(1, NUM_CUSTOMERS),

        "order_date": dt.strftime("%Y-%m-%d %H:%M:%S"),

        "status": random.choice(statuses),

        "region_code": random.choice(regions)

    })

In [0]:
num_null = int(NUM_ORDERS * 0.05)

indices = random.sample(range(NUM_ORDERS), num_null)

for i in indices:

    orders[i]["customer_id"] = None

In [0]:
num_wrong = int(NUM_ORDERS * 0.03)

indices = random.sample(range(NUM_ORDERS), num_wrong)

for i in indices:

    dt = datetime.strptime(
        orders[i]["order_date"],
        "%Y-%m-%d %H:%M:%S"
    )

    orders[i]["order_date"] = dt.strftime("%d-%m-%Y")

In [0]:
orders_df = pd.DataFrame(orders)

In [0]:
order_items = []

for i in range(1, NUM_ORDER_ITEMS + 1):

    order_items.append({

        "item_id": i,

        "order_id": random.randint(1, NUM_ORDERS),

        "product_id": random.randint(1, NUM_PRODUCTS),

        "quantity": random.randint(1,5),

        "unit_price": round(
            random.uniform(100,5000),2
        ),

        "discount_percent": random.randint(0,50)

    })

In [0]:
num_negative = int(NUM_ORDER_ITEMS * 0.03)

indices = random.sample(range(NUM_ORDER_ITEMS), num_negative)

for i in indices:

    order_items[i]["quantity"] = -random.randint(1,3)

In [0]:
num_invalid = int(NUM_ORDER_ITEMS * 0.02)

indices = random.sample(range(NUM_ORDER_ITEMS), num_invalid)

for i in indices:

    order_items[i]["order_id"] = 999999

In [0]:
order_items_df = pd.DataFrame(order_items)

In [0]:
customers_df.to_csv("customers.csv", index=False)

products_df.to_csv("products.csv", index=False)

orders_df.to_csv("orders.csv", index=False)

order_items_df.to_csv("order_items.csv", index=False)

In [0]:
print(customers_df.head())

print(products_df.head())

print(orders_df.head())

print(order_items_df.head())

   customer_id      customer_name  ... registration_date customer_type
0            1       Allison Hill  ...        2026-03-22       PREMIUM
1            2     Javier Johnson  ...        2024-02-21       REGULAR
2            3  Kimberly Robinson  ...        2024-10-24       REGULAR
3            4   Daniel Gallagher  ...        2025-05-10       PREMIUM
4            5     Monica Herrera  ...        2025-05-26       REGULAR

[5 rows x 5 columns]
   product_id product_name     category subcategory  cost_price
0           1        Chair         Home       Chair     3596.37
1           2       Jacket     Clothing      Jacket     1745.65
2           3        Phone  Electronics       Phone      839.07
3           4        Table         Home       Table     3561.45
4           5   Headphones  Electronics  Headphones     2097.24
   order_id  customer_id           order_date     status region_code
0         1         12.0  2025-07-20 21:41:01  CANCELLED        EAST
1         2        419.0  2025-11-15 03:41:22     PLACED       SOUTH
2         3        297.0  2026-03-30 12:20:20     PLACED       NORTH
3         4        217.0  2026-02-28 05:48:05  DELIVERED       NORTH
4         5        278.0  2025-10-10 14:54:44     PLACED       NORTH
   item_id  order_id  product_id  quantity  unit_price  discount_percent
0        1       468         422         4     3730.63                48
1        2       265         445         3     4122.99                32
2        3       406          82         1     1624.50                32
3        4       207          70         5     4408.73                 1
4        5        89          99        -3     4201.19                15

In [0]:
customers = pd.read_csv("customers.csv")

products = pd.read_csv("products.csv")

orders = pd.read_csv("orders.csv")

order_items = pd.read_csv("order_items.csv")

In [0]:
print(customers.isnull().sum())

print(products.isnull().sum())

print(orders.isnull().sum())

print(order_items.isnull().sum())

customer_id          0
customer_name        0
email                0
registration_date    0
customer_type        0
dtype: int64
product_id      0
product_name    0
category        0
subcategory     0
cost_price      0
dtype: int64
order_id        0
customer_id    25
order_date      0
status          0
region_code     0
dtype: int64
item_id             0
order_id            0
product_id          0
quantity            0
unit_price          0
discount_percent    0
dtype: int64

In [0]:
customers.drop_duplicates(inplace=True)

products.drop_duplicates(inplace=True)

orders.drop_duplicates(inplace=True)

order_items.drop_duplicates(inplace=True)

In [0]:
customers["customer_name"] = customers["customer_name"].fillna("Unknown")

In [0]:
pattern = r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'

In [0]:
customers["valid_email"] = customers["email"].str.match(pattern, na=False)

In [0]:
invalid_emails = customers[customers["valid_email"] == False]

print(invalid_emails)

     customer_id      customer_name  ... customer_type valid_email
63            64    Leslie Alvarado  ...       REGULAR       False
160          161      Robert Monroe  ...       REGULAR       False
169          170    Jeremy Mitchell  ...       PREMIUM       False
319          320        Donna Adams  ...           VIP       False
339          340    Dennis Williams  ...           VIP       False
340          341     Jennifer Miles  ...           VIP       False
368          369  Danielle Phillips  ...           VIP       False
434          435       Martha Smith  ...           VIP       False
471          472     Priscilla Berg  ...       PREMIUM       False
485          486       Kimberly May  ...       PREMIUM       False

[10 rows x 6 columns]

In [0]:
products["product_name"] = products["product_name"].str.strip()

In [0]:
products["product_name"] = products["product_name"].str.title()

In [0]:
products.drop_duplicates(subset="product_id", inplace=True)

In [0]:
orders["customer_id"] = orders["customer_id"].fillna(0)

In [0]:
orders["order_date"] = pd.to_datetime(

    orders["order_date"],

    errors="coerce",

    dayfirst=True

)

/home/spark-6b719353-e1b3-436f-9051-e2/.ipykernel/333/command-7016587559359698-3921720931:1: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  orders["order_date"] = pd.to_datetime(

In [0]:
orders["order_date"] = orders["order_date"].dt.strftime("%Y-%m-%d %H:%M:%S")

In [0]:
orders = orders.dropna(subset=["order_date"])

In [0]:
order_items = order_items[order_items["quantity"] > 0]

In [0]:
order_items = order_items[
    order_items["discount_percent"] <= 100
]

In [0]:
invalid_orders = order_items[
    ~order_items["order_id"].isin(
        orders["order_id"]
    )
]

In [0]:
print(invalid_orders)

     item_id  order_id  product_id  quantity  unit_price  discount_percent
8          9       191         251         5     2285.91                30
11        12        26          84         5     3921.17                13
21        22    999999         145         3     3453.62                30
36        37       191         134         5     1540.85                 7
51        52       160          67         1     1979.40                37
81        82       191         418         3      996.06                25
91        92    999999         393         5     3646.49                14
100      101       419         121         1     2349.56                36
120      121       472         467         2     3489.91                11
123      124    999999         312         2     1440.62                21
157      158    999999         386         5     2699.44                35
166      167    999999         274         1     3171.97                13
213      214    999999         375         4     4701.96                 2
221      222       460         428         1     2631.65                24
223      224       419         445         3     2485.62                30
226      227       144         109         2     1015.84                23
242      243       244         462         5     3039.09                50
245      246       460         481         4     2658.02                23
290      291       244         161         3     1170.97                36
305      306    999999         186         5     4323.03                11
309      310       144         231         2     2899.91                36
361      362       191         238         1     1718.22                48
364      365       419         196         1      697.61                49
376      377       191         395         1     1318.74                31
397      398    999999         329         4     3323.81                33
408      409    999999         327         5     1854.02                29
412      413    999999         181         3     2795.40                20
469      470       460         202         2      530.20                24
518      519       244         233         4     2265.19                38
521      522        26          95         2      369.81                22
553      554       144         431         1     1761.85                24
569      570       160         328         2     1672.31                12
577      578        26          55         4      363.62                27
648      649       244         155         4     3756.14                48
662      663    999999          30         5     3317.37                13
669      670    999999         142         1     1975.72                21
676      677       460         255         2     3299.04                 0
729      730       460         167         2     3916.98                20
736      737       144          70         1     4273.09                29
766      767       191         177         4     2482.51                33
770      771    999999          42         4     4499.93                18
789      790    999999         500         2     2714.85                 7
790      791       472          13         4     4662.24                49
798      799    999999         183         1     1699.20                38
835      836       191         399         4     2118.77                10
859      860       244         188         5     1007.12                43
872      873    999999         457         2      417.08                12
886      887    999999          10         1     4954.49                 7
902      903        11         276         3      283.15                42
907      908       173         255         5     4076.14                42
939      940       122         308         1     3888.64                20
945      946       244         350         2     4820.25                50
977      978    999999         106         5     1156.28                18
988      989    999999         344         3      747.97                35

In [0]:
order_items = order_items[
    order_items["order_id"].isin(
        orders["order_id"]
    )
]

In [0]:
invalid_products = order_items[
    ~order_items["product_id"].isin(
        products["product_id"]
    )
]

print(invalid_products)

Empty DataFrame
Columns: [item_id, order_id, product_id, quantity, unit_price, discount_percent]
Index: []

In [0]:
invalid_products = order_items[
    ~order_items["product_id"].isin(
        products["product_id"]
    )
]

print(invalid_products)

Empty DataFrame
Columns: [item_id, order_id, product_id, quantity, unit_price, discount_percent]
Index: []

In [0]:
customers.to_csv(
    "customers_clean.csv",
    index=False
)

products.to_csv(
    "products_clean.csv",
    index=False
)

orders.to_csv(
    "orders_clean.csv",
    index=False
)

order_items.to_csv(
    "order_items_clean.csv",
    index=False
)

In [0]:
print("========== CLEANING COMPLETED ==========")

print("Customers :", len(customers))

print("Products :", len(products))

print("Orders :", len(orders))

print("Order Items :", len(order_items))

========== CLEANING COMPLETED ==========
Customers : 500
Products : 500
Orders : 485
Order Items : 916

In [0]:
%sql
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS order_items;

In [0]:
customers_spark = spark.createDataFrame(customers)
products_spark = spark.createDataFrame(products)
orders_spark = spark.createDataFrame(orders)
order_items_spark = spark.createDataFrame(order_items)

customers_spark.write.mode("overwrite").saveAsTable("customers")
products_spark.write.mode("overwrite").saveAsTable("products")
orders_spark.write.mode("overwrite").saveAsTable("orders")
order_items_spark.write.mode("overwrite").saveAsTable("order_items")